spring:
  datasource:
    url: url
    username: username
    password: pass

  jpa:
    show-sql: true
    hibernate:
      format_sql: true

  liquibase:
    change-log: classpath:db\changelog\db.changelog-master.yaml