spring:
  datasource:
    url: jdbc:postgresql://localhost/dev
    username: dev
    password: dev
    schema: liquibasedb

  output:
    ansi:
      enabled: ALWAYS

  logging:
    level:
      org.hibernate.SQL: DEBUG

  liquibase:
    change-log: classpath:db\changelog\db.changelog-master.yaml